name: CI - Backend

on:
  pull_request:
  push:
    branches: [ ci-pipeline ]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true

      - name: Install Dependencies
        run: |
          sudo apt-get update -qq && \
          sudo apt-get install --no-install-recommends -y build-essential git libpq-dev libyaml-dev pkg-config && \
          rm -rf /var/lib/apt/lists /var/cache/apt/archives

      - name: Install Gems
        run: |
          bundle install && \
          rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
          bundle exec bootsnap precompile --gemfile

      - name: Lint code for consistent style
        run: bin/rubocop -f github
